module.exports = {
    'is': '+',
    'add': '+',
    '=': '+',
    'isnot': '-',
    'isnt': '-',
    'remove': '-',
    'is!': '-',
    '!': '-',
    '/': '?',
    'is?': '?',
    'size': '?',
    'is?!': '?!',
    'with': '+=',
    'without': '-=',
    'from': ':',
    'each': '_',
    'import': '<<',
    'export': '>>',
    'require': '$',
    '@log': '@print',
    '@debug': '@print?'
};
